# Generated by Django 4.2.1 on 2023-05-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_class',
        ),
        migrations.AddField(
            model_name='seat',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='category',
            field=models.CharField(default='economy', max_length=10),
        ),
        migrations.AddField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flight_seats', to='airline_api.flight'),
        ),
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats',
            field=models.ManyToManyField(related_name='flights', through='airline_api.FlightSeat', to='airline_api.seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
