# Generated by Django 4.2.1 on 2023-05-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0002_remove_seat_name_remove_seat_seat_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='airline_api.booking'),
        ),
    ]
