# Generated by Django 4.2.1 on 2023-05-09 13:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0007_alter_booking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='luggage',
            field=jsonfield.fields.JSONField(),
        ),
    ]
