# Generated by Django 4.2.1 on 2023-05-10 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0008_alter_customer_luggage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
