# Generated by Django 4.2.1 on 2023-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0011_alter_seat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(default='England', max_length=10),
            preserve_default=False,
        ),
    ]
