# Generated by Django 4.2.1 on 2023-05-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0012_airport_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.IntegerField(),
        ),
    ]
