# Generated by Django 4.2.1 on 2023-05-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0015_alter_seat_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.CharField(max_length=20),
        ),
    ]
